"""
build_inventory.py — standalone on-hand filament inventory workbook.

Separated from the per-brand catalog workbooks (2026-07-23) so that:
  - Catalog workbooks can be freely regenerated from their scripts without
    any risk of overwriting real owned-spool data.
  - All 11 brands' inventory lives in one place instead of 11 separate
    Inventory Tracker sheets.
  - The "phantom template row" bug class (hundreds of pre-filled formula
    rows silently counted as real inventory by naive tooling) is avoided
    by using a much smaller, single pool of headroom rows instead of
    700-per-brand.

Run: python build_inventory.py
"""
import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(__file__))
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font
from openpyxl.styles.differential import DifferentialStyle
from openpyxl.formatting.rule import Rule
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

from template_v3 import (
    P, FONT_NAME, _argb, _font, _sc, _header_row, _set_widths, _merge,
    _section, _dv, _align, next_versioned_path,
)

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

BRANDS = [
    "AzureFilm", "Bambu Lab", "Creality Hyper", "Hatchbox", "MatterHackers",
    "Overture", "Polymaker", "Prusament", "SUNLU", "VoxelPLA", "eSUN",
]

HEADROOM_ROWS = 50   # modest pre-filled formula headroom, not 700 — see module docstring
DATA_START = 3

INV_HEADERS = [
    "Brand", "SKU", "Material Type", "Product Name", "Color Name",
    "Color Swatch", "Hex Code", "Diameter", "Lot / Batch Code",
    "Date Purchased", "Where Purchased", "List Price", "Price Paid",
    "Quantity in Stock", "Reorder Flag", "Opened / Sealed", "Condition",
    "Moisture Rating", "Last Dried Date", "Notes", "Total Value",
]
INV_WIDTHS = [16, 18, 14, 24, 18, 10, 10, 9, 18, 14, 20, 12, 12, 16, 14, 14, 12, 14, 14, 36, 14]
# Column letters: A Brand, B SKU, ... N Qty in Stock, O Reorder Flag,
# ... M Price Paid, ... T Notes, U Total Value
COL = {h: get_column_letter(i + 1) for i, h in enumerate(INV_HEADERS)}


def _build_config(wb: Workbook, file_version: str = "v?"):
    ws = wb.create_sheet("Config")
    ws.sheet_properties.tabColor = "7F7F7F"
    _merge(ws, 1, 1, 1, 3, "⚙  Configuration", bg=P["hdr_bg"], size=12)
    ws.row_dimensions[1].height = 26
    _header_row(ws, 2, ["Setting", "Value", "Notes"], bg=P["sec_bg"], height=22)

    settings = [
        ("Reorder Threshold", 1,
         "Reorder Flag fires when Qty in Stock <= this value"),
        ("File Version", file_version, ""),
        ("Generated", date.today().isoformat(),
         "Date this file was last generated by build_inventory.py"),
        ("Scope Note",
         "Covers on-hand spool inventory only, across all 11 brand catalogs. "
         "Catalog reference data (colors, hex, SKUs, tiers) lives in the per-brand workbooks.",
         "Split from per-brand Inventory Tracker sheets, 2026-07-23"),
    ]
    for i, (label, val, note) in enumerate(settings, 3):
        ws.cell(row=i, column=1, value=label)
        c = ws.cell(row=i, column=2, value=val)
        ws.cell(row=i, column=3, value=note)
        _sc(ws.cell(row=i, column=1), bold=True)
        _sc(c, bg=P["cfg_bg"], fg=P["cfg_fg"], bold=(i == 3), align="center")
        _sc(ws.cell(row=i, column=3), italic=True)
        ws.row_dimensions[i].height = 18
    _set_widths(ws, [20, 56, 70])


def _build_inventory(wb: Workbook, entries: list):
    ws = wb.create_sheet("Inventory")
    ws.freeze_panes = "C3"
    ws.sheet_properties.tabColor = "375623"

    _merge(ws, 1, 1, 1, len(INV_HEADERS),
           "Filament Inventory — On-Hand Spools (All Brands)",
           bg=P["hdr_bg"], size=13)
    ws.row_dimensions[1].height = 26
    _header_row(ws, 2, INV_HEADERS, bg=P["sec_bg"], height=28)

    row = DATA_START
    for e in entries:
        for h in INV_HEADERS:
            col_idx = INV_HEADERS.index(h) + 1
            if h == "Reorder Flag":
                val = (f'=IF(OR(N{row}="",Config!$B$3=""),"",'
                       f'IF(N{row}<=Config!$B$3,"\u26a0 REORDER",""))')
            elif h == "Total Value":
                val = f'=IF(OR(M{row}="",N{row}=""),0,M{row}*N{row})'
            elif h == "Color Swatch":
                val = None
            else:
                val = e.get(h)
            cell = ws.cell(row=row, column=col_idx, value=val)
            _sc(cell, align="center" if h in
                ("SKU", "Diameter", "Quantity in Stock", "Reorder Flag",
                 "Opened / Sealed", "Condition", "Moisture Rating") else "left")
        hexv = e.get("Hex Code")
        if hexv:
            swatch_col_idx = INV_HEADERS.index("Color Swatch") + 1
            ws.cell(row=row, column=swatch_col_idx).fill = \
                PatternFill(fill_type="solid", fgColor="FF" + hexv.lstrip("#").upper())
        ws.cell(row=row, column=INV_HEADERS.index("List Price") + 1).number_format = "$#,##0.00"
        ws.cell(row=row, column=INV_HEADERS.index("Price Paid") + 1).number_format = "$#,##0.00"
        ws.cell(row=row, column=INV_HEADERS.index("Total Value") + 1).number_format = "$#,##0.00"
        ws.cell(row=row, column=INV_HEADERS.index("Quantity in Stock") + 1).number_format = "#,##0"
        ws.row_dimensions[row].height = 20
        row += 1

    # Modest pre-filled headroom (formulas only), not hundreds per brand
    populated = len(entries)
    for extra in range(DATA_START + populated, DATA_START + populated + HEADROOM_ROWS):
        rfc = ws.cell(row=extra, column=INV_HEADERS.index("Reorder Flag") + 1,
                      value=f'=IF(OR(N{extra}="",Config!$B$3=""),"",'
                            f'IF(N{extra}<=Config!$B$3,"\u26a0 REORDER",""))')
        _sc(rfc, align="center", border=True)
        tvc = ws.cell(row=extra, column=INV_HEADERS.index("Total Value") + 1,
                      value=f'=IF(OR(M{extra}="",N{extra}=""),0,M{extra}*N{extra})')
        _sc(tvc, align="center", border=True)
        ws.cell(row=extra, column=INV_HEADERS.index("Quantity in Stock") + 1).number_format = "#,##0"
        ws.cell(row=extra, column=INV_HEADERS.index("Total Value") + 1).number_format = "$#,##0.00"

    last_row = DATA_START + populated + HEADROOM_ROWS - 1

    # Data validations
    for col_name, formula in [
        ("Brand", '"' + ",".join(BRANDS) + '"'),
        ("Opened / Sealed", '"Opened,Sealed"'),
        ("Condition", '"New,Good,Fair,Poor"'),
        ("Moisture Rating", '"Dry,OK,Damp,Wet"'),
        ("Diameter", '"1.75mm,2.85mm"'),
    ]:
        dv = _dv(formula)
        col = COL[col_name]
        dv.sqref = f"{col}{DATA_START}:{col}{last_row}"
        ws.add_data_validation(dv)

    # Conditional formatting: reorder flag + damp/wet + opened warning
    ds_warn = DifferentialStyle(
        font=Font(name=FONT_NAME, bold=True, color=_argb(P["warn_fg"])),
        fill=PatternFill(bgColor=_argb(P["warn_bg"])))
    reorder_col = COL["Reorder Flag"]
    ws.conditional_formatting.add(
        f"{reorder_col}{DATA_START}:{reorder_col}{last_row}",
        Rule(type="containsText", operator="containsText", text="REORDER",
             formula=[f'NOT(ISERROR(SEARCH("REORDER",{reorder_col}{DATA_START})))'],
             dxf=ds_warn))

    ws.auto_filter.ref = f"A2:{get_column_letter(len(INV_HEADERS))}{last_row}"
    _set_widths(ws, INV_WIDTHS)


def _build_dashboard(wb: Workbook, entries: list):
    ws = wb.create_sheet("Dashboard")
    ws.sheet_properties.tabColor = P["hdr_bg"]
    ncols = 6
    _merge(ws, 1, 1, 1, ncols, "Filament Inventory — Dashboard", bg=P["hdr_bg"], size=14)
    ws.row_dimensions[1].height = 30

    r = 3
    _section(ws, r, "  SUMMARY", ncols)
    r += 1
    last_data_row = DATA_START + len(entries) + HEADROOM_ROWS - 1
    pairs = [
        ("Total Spools in Stock", f"=SUM(Inventory!N{DATA_START}:N{last_data_row})", None),
        ("Total Inventory Value",
         (f"=SUMPRODUCT(IF(Inventory!M{DATA_START}:M{last_data_row}=\"\",0,"
          f"Inventory!M{DATA_START}:M{last_data_row})*"
          f"IF(Inventory!N{DATA_START}:N{last_data_row}=\"\",0,"
          f"Inventory!N{DATA_START}:N{last_data_row}))"),
         "$#,##0.00"),
        ("Items at Reorder Point",
         f'=COUNTIF(Inventory!O{DATA_START}:O{last_data_row},"*REORDER*")', None),
        ("Reorder Threshold (from Config)", "=Config!$B$3", None),
    ]
    for label, formula, fmt in pairs:
        lc = ws.cell(row=r, column=1, value=label)
        _sc(lc, bold=True)
        ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=3)
        vc = ws.cell(row=r, column=2, value=formula)
        _sc(vc, bg=P["cfg_bg"], fg=P["cfg_fg"], bold=True, align="center")
        if fmt:
            vc.number_format = fmt
        ws.row_dimensions[r].height = 20
        r += 1

    r += 1
    _section(ws, r, "  BY BRAND", ncols)
    r += 1
    for hdr, col in (("Brand", 1), ("Spools in Stock", 2), ("Total Value", 3)):
        h = ws.cell(row=r, column=col, value=hdr)
        _sc(h, bg=P["sec_bg"], fg=P["sec_fg"], bold=True, align="center")
    ws.row_dimensions[r].height = 22
    for brand in BRANDS:
        r += 1
        ws.cell(row=r, column=1, value=brand)
        _sc(ws.cell(row=r, column=1))
        qc = ws.cell(row=r, column=2,
                     value=f'=IFERROR(SUMIF(Inventory!A{DATA_START}:A{last_data_row},A{r},'
                           f'Inventory!N{DATA_START}:N{last_data_row}),0)')
        _sc(qc, align="center")
        qc.number_format = "#,##0"
        vc = ws.cell(row=r, column=3,
                     value=(f'=IFERROR(SUMPRODUCT('
                            f'(Inventory!A{DATA_START}:A{last_data_row}=A{r})*'
                            f'IF(Inventory!M{DATA_START}:M{last_data_row}="",0,Inventory!M{DATA_START}:M{last_data_row})*'
                            f'IF(Inventory!N{DATA_START}:N{last_data_row}="",0,Inventory!N{DATA_START}:N{last_data_row})),0)'))
        _sc(vc, align="center")
        vc.number_format = "$#,##0.00"
        ws.row_dimensions[r].height = 18

    ws.column_dimensions["A"].width = 22
    for col in "BCDEF":
        ws.column_dimensions[col].width = 16


def build_inventory_workbook(entries: list, file_version: str = "v?") -> Workbook:
    wb = Workbook()
    wb.remove(wb.active)
    _build_dashboard(wb, entries)
    _build_inventory(wb, entries)
    _build_config(wb, file_version)
    return wb


if __name__ == "__main__":
    import json
    # Migrated from the 11 brand workbooks' Inventory Tracker sheets, 2026-07-23,
    # as part of splitting inventory out of the catalog workbooks.
    src_path = os.path.join(os.path.dirname(__file__), "real_inventory.json")
    with open(src_path, encoding="utf-8") as f:
        raw = json.load(f)
    ENTRIES = []
    for row in raw:
        ENTRIES.append({
            "Brand": row["Brand"],
            "SKU": row["SKU / Product ID"],
            "Material Type": row["Material Type"],
            "Product Name": row["Product Name"],
            "Color Name": row["Color Name"],
            "Hex Code": row["Hex Code"],
            "Diameter": row["Diameter"],
            "Lot / Batch Code": row.get("Lot / Batch Code"),
            "Date Purchased": row.get("Date Purchased"),
            "Where Purchased": row.get("Where Purchased"),
            "List Price": row.get("List Price"),
            "Price Paid": row.get("Price Paid"),
            "Quantity in Stock": row.get("Quantity in Stock"),
            "Opened / Sealed": row.get("Opened / Sealed"),
            "Condition": row.get("Condition"),
            "Moisture Rating": row.get("Moisture Rating"),
            "Last Dried Date": row.get("Last Dried Date"),
            "Notes": row.get("Notes"),
        })
    pattern  = r'^Filament_Inventory_v(\d+)\.xlsx$'
    template = 'Filament_Inventory_v{n}.xlsx'
    path, version, prev = next_versioned_path(OUTPUT_DIR, pattern, template)

    wb = build_inventory_workbook(ENTRIES, file_version=f"v{version}")
    wb.save(path)
    print(f"\u2713  {os.path.basename(path)}  ({len(ENTRIES)} spools)")
    print(f"   Written to: {path}")
    if prev:
        print(f"   ⚠  Delete old version from the repo after uploading: {prev}")
