"""
generate_azurefilm.py — AzureFilm filament workbook
Transcribed from the current production AzureFilm_filaments_v3.xlsx
(2026-07-23) so the generation script is in sync with the shipped catalog.
Sources: azurefilm.com product pages / TDS (see Tier Rationale per line).
Run: python generate_azurefilm.py
"""

import os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from template_v3 import build_workbook, next_versioned_path

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)


AZUREFILM = {
    "brand": "AzureFilm",
    "catalog": [
        dict(material_type="ABS", sku="AZ-ABS-BLK",
             product_name="AzureFilm ABS Plus", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="240–260°C", bed_temp="90–120°C",
             drying="70°C / 4h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Manufacturer product-page confirmed; enclosure required; AMS Lite unsuitable for ABS",
             notes=""),
        dict(material_type="ABS", sku="AZ-ABS-WHT",
             product_name="AzureFilm ABS Prime", color_name="White",
             color_hex="F0F0EA", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="240–265°C", bed_temp="70–100°C",
             drying="70°C / 4h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Manufacturer product-page confirmed; zero-warping formula; enclosure recommended; AMS Lite ✗",
             notes=""),
        dict(material_type="ASA", sku="AZ-ASA-BLK",
             product_name="AzureFilm ASA Original", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="240–260°C", bed_temp="90–120°C",
             drying="70°C / 4h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); enclosure required; UV/weather-resistant",
             notes=""),
        dict(material_type="ASA", sku="AZ-ASA-GRY",
             product_name="AzureFilm ASA Prime", color_name="Grey",
             color_hex="7C7F82", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="240–260°C", bed_temp="90–120°C",
             drying="70°C / 4h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); enclosure required; UV/weather-resistant",
             notes=""),
        dict(material_type="PETG", sku="AZ-PET-BLK",
             product_name="AzureFilm PETG", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="220–240°C", bed_temp="80–90°C",
             drying="65°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PETG", sku="AZ-PET-CLR",
             product_name="AzureFilm PETG", color_name="Clear / Natural",
             color_hex="E7F2F1", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="220–240°C", bed_temp="80–90°C",
             drying="65°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes="Translucent"),
        dict(material_type="PETG", sku="AZ-PET-WHT",
             product_name="AzureFilm PETG", color_name="White",
             color_hex="F0F0EA", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="220–240°C", bed_temp="80–90°C",
             drying="65°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-BLK",
             product_name="AzureFilm Original PLA", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-SMN-BLK",
             product_name="AzureFilm Strongman PLA", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="50°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Toughened PLA blend; manufacturer TDS-confirmed (azurefilm.com)",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-BLU",
             product_name="AzureFilm Original PLA", color_name="Blue",
             color_hex="1F5FA8", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-EMR",
             product_name="AzureFilm Original PLA", color_name="Emerald Green",
             color_hex="285D5E", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes="Hex colorimeter-confirmed (filamentcolors.xyz)"),
        dict(material_type="PLA", sku="AZ-PLA-GRY",
             product_name="AzureFilm Original PLA", color_name="Grey",
             color_hex="8D989D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes="Hex colorimeter-confirmed (filamentcolors.xyz)"),
        dict(material_type="PLA", sku="AZ-SMN-GRY",
             product_name="AzureFilm Strongman PLA", color_name="Grey",
             color_hex="8A8F94", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="50°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Toughened PLA blend; manufacturer TDS-confirmed (azurefilm.com)",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-LGR",
             product_name="AzureFilm Original PLA", color_name="Light Green",
             color_hex="8CC63F", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-ORG",
             product_name="AzureFilm Original PLA", color_name="Orange",
             color_hex="EA7125", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-PUR",
             product_name="AzureFilm Original PLA", color_name="Purple",
             color_hex="6E3F8F", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-RED",
             product_name="AzureFilm Original PLA", color_name="Red",
             color_hex="C81E2C", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-WHT",
             product_name="AzureFilm Original PLA", color_name="White",
             color_hex="F3F3EB", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes="Hex colorimeter-confirmed (filamentcolors.xyz)"),
        dict(material_type="PLA", sku="AZ-SMN-WHT",
             product_name="AzureFilm Strongman PLA", color_name="White",
             color_hex="F2F2ED", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="50°C / 6h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Toughened PLA blend; manufacturer TDS-confirmed (azurefilm.com)",
             notes=""),
        dict(material_type="PLA", sku="AZ-PLA-YEL",
             product_name="AzureFilm Original PLA", color_name="Yellow",
             color_hex="F4C61F", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); standard reel, not Bambu-verified",
             notes=""),
        dict(material_type="PLA Glitter", sku="AZ-GLT-BLU",
             product_name="AzureFilm Glitter PLA", color_name="Blue Glitter",
             color_hex="1D4E8F", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="210–225°C", bed_temp="55–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Glitter fill; 0.4mm+ nozzle recommended; temps not manufacturer-confirmed",
             notes=""),
        dict(material_type="PLA Glitter", sku="AZ-GLT-RED",
             product_name="AzureFilm Glitter PLA", color_name="Red Glitter",
             color_hex="A31E2E", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="210–225°C", bed_temp="55–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Glitter fill; 0.4mm+ nozzle recommended; temps not manufacturer-confirmed",
             notes=""),
        dict(material_type="PLA Pastel", sku="AZ-PST-BBL",
             product_name="AzureFilm Pastel PLA", color_name="Baby Blue",
             color_hex="AED6E8", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="195–215°C", bed_temp="50–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Standard pastel PLA; temps not manufacturer-confirmed",
             notes=""),
        dict(material_type="PLA Pastel", sku="AZ-PST-MNT",
             product_name="AzureFilm Pastel PLA", color_name="Mint",
             color_hex="B8E3C8", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="195–215°C", bed_temp="50–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="B",
             tier_rationale="Standard pastel PLA; temps not manufacturer-confirmed",
             notes=""),
        dict(material_type="PLA Silk", sku="AZ-SLK-CPR",
             product_name="AzureFilm Silk PLA", color_name="Copper",
             color_hex="B36A4E", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="210–240°C", bed_temp="70–80°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); silk finish prints best slower",
             notes=""),
        dict(material_type="PLA Silk", sku="AZ-SLK-GLD",
             product_name="AzureFilm Silk PLA", color_name="Gold",
             color_hex="C9A24B", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="210–240°C", bed_temp="70–80°C (not required)",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="A",
             tier_rationale="Manufacturer TDS-confirmed (azurefilm.com); silk finish prints best slower",
             notes=""),
        dict(material_type="PLA Wood", sku="AZ-WOD-BAM",
             product_name="AzureFilm LumberLay Wood PLA", color_name="Bamboo",
             color_hex="B08D57", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="195–215°C", bed_temp="50–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Wood-fill; larger nozzle recommended, mildly abrasive; temps not manufacturer-confirmed",
             notes=""),
        dict(material_type="TPU", sku="AZ-FLX-BLK",
             product_name="AzureFilm Flexible 85A", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="220–240°C", bed_temp="80°C",
             drying="50°C / 8h",
             ams_xp="✗", ams_lite="✗", ams_2pro="✗", ams_ht="✗",
             tier="B",
             tier_rationale="Flexible 85A shore; manufacturer product-page confirmed; external-spool-only on all Bambu AMS variants",
             notes=""),
        dict(material_type="TPU", sku="AZ-FLX-WHT",
             product_name="AzureFilm Flexible 85A", color_name="White",
             color_hex="EFEFEA", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="220–240°C", bed_temp="80°C",
             drying="50°C / 8h",
             ams_xp="✗", ams_lite="✗", ams_2pro="✗", ams_ht="✗",
             tier="B",
             tier_rationale="Flexible 85A shore; manufacturer product-page confirmed; external-spool-only on all Bambu AMS variants",
             notes=""),
        dict(material_type="PLA Matte", sku="AZ-MAT-01",
             product_name="AzureFilm PLA Matte", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–220°C", bed_temp="50–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Line existence confirmed (azurefilm.com nav: \"PLA Matte\"); full color list not verified this pass",
             notes="Deep-dive follow-up 2026-07-19; NEW LINE — not previously in catalog"),
        dict(material_type="PLA Prime", sku="AZ-PRIME-01",
             product_name="AzureFilm PLA Prime", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.02mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="200–230°C", bed_temp="50–60°C",
             drying="45°C / 4h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Line existence confirmed (azurefilm.com nav: \"PLA Prime\"); premium PLA tier, distinct from PLA Original/Strongman; specs estimated",
             notes="Deep-dive follow-up 2026-07-19; NEW LINE — not previously in catalog"),
        dict(material_type="PC-ABS", sku="AZ-PCABS-01",
             product_name="AzureFilm PC-ABS", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.05mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="250–270°C", bed_temp="90–110°C",
             drying="70°C / 8h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Line existence confirmed (azurefilm.com nav: \"PC ABS Filaments\"); enclosure required",
             notes="Deep-dive follow-up 2026-07-19; NEW LINE — not previously in catalog"),
        dict(material_type="PLA-CF", sku="AZ-CF-01",
             product_name="AzureFilm Carbon Fiber PLA", color_name="Black",
             color_hex="0D0D0D", diameter="1.75mm",
             diameter_tolerance="±0.05mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="210–230°C", bed_temp="50–70°C",
             drying="65°C / 8h",
             ams_xp="✓", ams_lite="✓", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Line existence confirmed (azurefilm.com nav: \"CARBON FIBER filaments\"); abrasive, hardened nozzle recommended",
             notes="Deep-dive follow-up 2026-07-19; NEW LINE — not previously in catalog"),
        dict(material_type="PA", sku="AZ-NYLON-01",
             product_name="AzureFilm Nylon", color_name="Natural",
             color_hex="F0EAE0", diameter="1.75mm",
             diameter_tolerance="±0.05mm", spool_type="Plastic",
             ams_adapter="No",
             print_temp="250–270°C", bed_temp="70–90°C",
             drying="80°C / 12h",
             ams_xp="✓", ams_lite="✗", ams_2pro="✓", ams_ht="✓",
             tier="C",
             tier_rationale="Line existence confirmed (azurefilm.com nav: \"NYLON filaments\"); very moisture-sensitive",
             notes="Deep-dive follow-up 2026-07-19; NEW LINE — not previously in catalog"),
    ],

    "inventory": [],

    "material_guide": [
        {
            "material":        "PLA",
            "print_temp":      "200–230°C",
            "bed_temp":        "50–60°C (not required)",
            "enclosure":       "No",
            "ams_compat":      "Yes",
            "drying_required": "Optional",
            "drying":          "45°C / 4h",
            "notes": "Original PLA — 10 core colors; manufacturer TDS-confirmed; ±0.02mm stated tolerance",
        },
        {
            "material":        "PLA (Strongman)",
            "print_temp":      "200–230°C",
            "bed_temp":        "50–60°C (not required)",
            "enclosure":       "No",
            "ams_compat":      "Yes",
            "drying_required": "Recommended",
            "drying":          "50°C / 6h",
            "notes": "Toughened PLA blend — manufacturer TDS-confirmed; higher impact resistance than standard PLA",
        },
        {
            "material":        "PLA (Silk)",
            "print_temp":      "210–240°C",
            "bed_temp":        "70–80°C (not required)",
            "enclosure":       "No",
            "ams_compat":      "Yes",
            "drying_required": "Optional",
            "drying":          "45°C / 4h",
            "notes": "Manufacturer TDS-confirmed; prints best slower to preserve shine",
        },
        {
            "material":        "PLA (Wood/Glitter/Pastel)",
            "print_temp":      "195–225°C",
            "bed_temp":        "50–60°C",
            "enclosure":       "No",
            "ams_compat":      "Yes",
            "drying_required": "Optional",
            "drying":          "45°C / 4h",
            "notes": "Effect PLAs — temps not independently manufacturer-confirmed; Glitter needs 0.4mm+ nozzle",
        },
        {
            "material":        "PETG",
            "print_temp":      "220–240°C",
            "bed_temp":        "80–90°C",
            "enclosure":       "No",
            "ams_compat":      "Yes",
            "drying_required": "Yes",
            "drying":          "65°C / 6h",
            "notes": "Manufacturer TDS-confirmed; Hyper Speed PETG line also available",
        },
        {
            "material":        "ABS Plus",
            "print_temp":      "240–260°C",
            "bed_temp":        "90–120°C",
            "enclosure":       "Yes",
            "ams_compat":      "⚠",
            "drying_required": "Yes",
            "drying":          "70°C / 4h",
            "notes": "Manufacturer product-page confirmed; enclosure required; AMS Lite ✗",
        },
        {
            "material":        "ABS Prime",
            "print_temp":      "240–265°C",
            "bed_temp":        "70–100°C",
            "enclosure":       "Yes",
            "ams_compat":      "⚠",
            "drying_required": "Yes",
            "drying":          "70°C / 4h",
            "notes": "Manufacturer product-page confirmed; zero-warping formula; enclosure recommended",
        },
        {
            "material":        "ASA",
            "print_temp":      "240–260°C",
            "bed_temp":        "90–120°C",
            "enclosure":       "Yes",
            "ams_compat":      "⚠",
            "drying_required": "Yes",
            "drying":          "70°C / 4h",
            "notes": "Manufacturer TDS-confirmed (Original + Prime); UV/weather resistant",
        },
        {
            "material":        "TPU (Flexible 85A)",
            "print_temp":      "220–240°C",
            "bed_temp":        "80°C",
            "enclosure":       "No",
            "ams_compat":      "No",
            "drying_required": "Yes",
            "drying":          "50°C / 8h",
            "notes": "Manufacturer product-page confirmed; AzureFilm markets this line as \"Flexible 85A\"; external spool only on all Bambu AMS variants",
        },
    ],
}


if __name__ == "__main__":
    pattern  = r'^AzureFilm_filaments_v3_(\d+)\.xlsx$'
    template = 'AzureFilm_filaments_v3_{n}.xlsx'
    path, version, prev = next_versioned_path(OUTPUT_DIR, pattern, template)

    wb = build_workbook(AZUREFILM)
    wb.save(path)
    n_cat = len(AZUREFILM["catalog"])
    print(f"✓  {os.path.basename(path)}  ({n_cat} catalog entries)")
    print(f"   Written to: {path}")
    if prev:
        print(f"   ⚠  Delete old version from the repo after uploading: {prev}")
